#!/bin/bash
# GitHub 仓库设置脚本

echo "========================================="
echo "长寿医学临床干预模型 - GitHub 仓库设置"
echo "========================================="
echo ""
echo "由于环境中未安装 GitHub CLI，请按以下步骤手动创建仓库："
echo ""
echo "1. 访问 https://github.com/new"
echo "2. 仓库名称: longevity-clinical-intervention"
echo "3. 描述: 基于科学证据的长寿医学临床干预模型系统"
echo "4. 设置为 Public 或 Private（根据需要）"
echo "5. 不要初始化 README、.gitignore 或 license（已包含在项目中）"
echo "6. 点击 'Create repository'"
echo ""
echo "创建后，运行以下命令推送代码："
echo ""
echo "cd /root/.openclaw/workspace/longevity-clinical-intervention"
echo "git remote add origin https://github.com/YOUR_USERNAME/longevity-clinical-intervention.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "将 YOUR_USERNAME 替换为你的 GitHub 用户名"
echo "========================================="
